### ISSUE TITLE
Right aligning more than one element in top level menu

### ISSUE THREAD

**Issue by giorgiopagnoni** [vadikom/smartmenus#40]
I'm floating three items to the right of my top level menu. Because of this right float, their HTML order has to be reversed, and as a consequence of this the order of the items in the desktop mode is different from the order in the collapsed mode.

<img width="625" alt="screen shot 2016-01-15 at 15 08 04" src="https://cloud.githubusercontent.com/assets/7541741/12355069/83221f30-bb9a-11e5-82c6-ddd4c1be3c29.png">
<img width="615" alt="screen shot 2016-01-15 at 15 08 21" src="https://cloud.githubusercontent.com/assets/7541741/12355068/831e78a8-bb9a-11e5-9593-7e49bb4b940b.png">

This isn't really a problem in your plugin, but I wonder if we can find some javascript magic or some html workaraound to make it possible and compatible with smartmenus.
Thank you!

**Comment by vadikom** [comment]
Sorry for the delay of this answer! There is one trick that comes to my mind right now that you could use - something like this:
```html
<li class="your-last-3-items-class"><a href="#">Item text</a> ...
```
```css
@media (min-width: 768px) {
	#main-menu {
		text-align: right;
	}
	#main-menu ul {
		text-align: left;
	}
	#main-menu .your-last-3-items-class {
		float: none;
		display: inline-block;
		margin-left: -4px; /* remove inline-blocks 4px spacing */
	}
}
```
Instead of right floating the last 3 items, you can make them inline blocks and right align them by setting the root UL's `text-align` to `right`.

Cheers!
