### ISSUE TITLE
long dropdowns

### ISSUE THREAD

**Issue by gtbu** [vadikom/smartmenus#87]
If i have a dropdown longer then 10 li-s  then an arrow appears - which is quite  a good solution.
Another solution would be a pseudo-megamenu like in
http://deluxe-menu.com/data-templates/blue-menu-template-sample.html 
or http://deluxe-menu.com/data-templates/elegant-dark-menu-template-sample.html
which makes parallel rows from 5 Elements on
e1 e2 e3 
e4 e5 e6
e7 e8 e9
...
Is this somehow possible with smartmenu - or can You add this option ?

**Comment by vadikom** [comment]
You can achieve it with CSS:
```css
@media (min-width: 768px) {
	ul.menu-cols {
		width: 40em !important;
		max-width: none !important;
		min-width: 0 !important;
	}
	ul.menu-cols > li {
		float: left;
		width: 33.33%; /* use 50% for 2 columns, etc. */
	}
}
```
and then set the class `menu-cols` to some sub menu's `<ul>` element.
