### ISSUE TITLE
Menu doesn't always work on ipad pro and displays at the wrong position the drop down

### ISSUE THREAD

**Issue by Jossnaz** [vadikom/smartmenus#92]
great plugin! thanks a lot. Really enjoy using it

I came across this issue, go to http://ironscales.com open it in chrome. Use the dev tools and emulate ipad pro. Use landscape mode. you will notice: not all menus open the drop down, and the one that does open (resources) does not fit the screen correctly, is cut off on the left side:
see here:
![image](https://user-images.githubusercontent.com/2072058/46830533-7f3f1900-cd66-11e8-8fe8-9a40c3e5b500.png)

**Comment by vadikom** [comment]
Hi and sorry for the delay! Unfortunately, it's been very busy times here lately.

To fix the issues you would need to:

1) In https://ironscales.com/js/irn.js in the following function:

```javascript
    _disableClickOnEmpty: function () {
      $('#main-menu a').on('click', function (ev) {
        var jthis = $(this);
        var href = jthis.attr('href');
        if (href == '#' || href == "#!") {
          ev.preventDefault();
          //return false;
        }
      });
    },
```

comment out/delete the `return false;` line. It interferes with SmartMenus' click handler and is not really needed (`ev.preventDefault()` alone does the job you need).

2) In your CSS find the following rule:
```css
/* line 137, ../scss/menu/_menu.scss */
.irn-menu-sub {
  transform: translateX(-50%);
}
```

and change it to something like this:
```css
/* line 137, ../scss/menu/_menu.scss */
.irn-menu-sub {
  transform: translateX(-50%);
  margin-left: 0 !important; // make sure SmartMenus' positioning is overriden since we are using our own positioning code in irn.menu.init
}
```
I hope this helps!

In the future please post similar support requests in the forums:

https://www.smartmenus.org/support/forums/

or if you like, opt for our [Premium support](https://www.smartmenus.org/support/premium-support/) plans where you are supposed to receive a response within 24 hours.

We'd prefer to use the GitHub Issues tracker just for bugs.

Thanks!
