### ISSUE TITLE
Please add option for submenu offset top

### ISSUE THREAD

**Issue by ve3** [vadikom/smartmenus#95]
An example from this demo page ( http://vadikom.github.io/smartmenus/src/demo/ )
The sub menu from **Sub test** > **more...**.
This sub menu is very long. My page has a stick top navbar and this submenu cannot set z-index higher than the navbar and then it stuck at under the navbar.

Please add an option that this submenu can set offset from top of the page.

**Comment by vadikom** [comment]
Could you please post a live demo URL of your code? I suppose there should be a reasonably simple CSS fix for the issue you describe.

**Comment by ve3** [comment]
Here is an example. https://rundiz.github.io/rundiz-template-for-admin/
It is my admin template I made it for free.

On sidebar menu, go to **Sub menus** > **3**
Open the **3** sub menu and you will see very long sub menu that is disappear under the navbar.
It would be good if there is an offset top option. :)

**Comment by vadikom** [comment]
Is there any problem if you change the following:
```scss
@mixin rd-sidebar-inner {
    // this will becomes .rd-page-wrapper .rd-sidebar-inner inside @media (min-width: $minimum-sidebar-breakpoint)
    .rd-sidebar-inner {

        // ...

        z-index: ($z-index-sidebar + 1);// fix sticky menu cause the menu is under everything that contain `position: relative;`.
    }
}
```
to something like this:
```scss
@mixin rd-sidebar-inner {
    // this will becomes .rd-page-wrapper .rd-sidebar-inner inside @media (min-width: $minimum-sidebar-breakpoint)
    .rd-sidebar-inner {

        // ...

        z-index: ($z-index-navbar + 1);// fix sticky menu cause the menu is under everything that contain `position: relative;`. Also make sure the sub menus appear above the sticky header navbar.
    }
}
```
in:
https://raw.githubusercontent.com/Rundiz/rundiz-template-for-admin/master/assets/scss/rdta/layout/_mixins.scss

?

Apart from that I agree, a top/bottom/right/left offset settings for the viewport edge detection feature might be useful in some cases.
